--------------------------------------------------------
--  Fichier cr�� - mercredi-mai-05-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYESMISSION
--------------------------------------------------------

  CREATE TABLE "ZOUHOUR"."EMPLOYESMISSION" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"IDMISSION" VARCHAR2(20 BYTE), 
	"IDEMP1" VARCHAR2(20 BYTE), 
	"IDEMP2" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ZOUHOUR.EMPLOYESMISSION
SET DEFINE OFF;
Insert into ZOUHOUR.EMPLOYESMISSION (ID,NOM,IDMISSION,IDEMP1,IDEMP2) values ('12365','hhhh','12564','19100','19100');
Insert into ZOUHOUR.EMPLOYESMISSION (ID,NOM,IDMISSION,IDEMP1,IDEMP2) values ('191jft','facebook','0256','19100','556522');
--------------------------------------------------------
--  DDL for Index EMPLOYESMISSION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZOUHOUR"."EMPLOYESMISSION_PK" ON "ZOUHOUR"."EMPLOYESMISSION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYESMISSION
--------------------------------------------------------

  ALTER TABLE "ZOUHOUR"."EMPLOYESMISSION" ADD CONSTRAINT "EMPLOYESMISSION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ZOUHOUR"."EMPLOYESMISSION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYESMISSION
--------------------------------------------------------

  ALTER TABLE "ZOUHOUR"."EMPLOYESMISSION" ADD CONSTRAINT "EMPLOYESMISSION_FK1" FOREIGN KEY ("IDMISSION")
	  REFERENCES "ZOUHOUR"."MISSION" ("ID") ENABLE;
 
  ALTER TABLE "ZOUHOUR"."EMPLOYESMISSION" ADD CONSTRAINT "EMPLOYESMISSION_FK2" FOREIGN KEY ("IDEMP1")
	  REFERENCES "ZOUHOUR"."EMPLOYE" ("ID") ENABLE;
 
  ALTER TABLE "ZOUHOUR"."EMPLOYESMISSION" ADD CONSTRAINT "EMPLOYESMISSION_FK3" FOREIGN KEY ("IDEMP2")
	  REFERENCES "ZOUHOUR"."EMPLOYE" ("ID") ENABLE;
